"""add_usuario_historial_to_activo

Revision ID: 0f820c8ff5a5
Revises: bbfbef31a0f7
Create Date: 2026-07-02 15:10:02.510296

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0f820c8ff5a5'
down_revision: Union[str, Sequence[str], None] = 'bbfbef31a0f7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('documentos_licencias', schema=None) as batch_op:
        # batch_op.drop_index(batch_op.f('ix_documentos_licencias_id'))
        pass

    # op.drop_table('documentos_licencias')
    pass
    with op.batch_alter_table('documentos_activos', schema=None) as batch_op:
        # batch_op.drop_index(batch_op.f('ix_documentos_activos_id'))
        pass

    # op.drop_table('documentos_activos')
    pass
    with op.batch_alter_table('activos', schema=None) as batch_op:
        batch_op.add_column(sa.Column('usuario_historial', sa.JSON(), nullable=True))

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('activos', schema=None) as batch_op:
        batch_op.drop_column('usuario_historial')

    op.create_table('documentos_activos',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('activo_id', sa.INTEGER(), nullable=False),
    sa.Column('nombre_archivo', sa.VARCHAR(length=255), nullable=False),
    sa.Column('ruta_archivo', sa.VARCHAR(length=500), nullable=False),
    sa.Column('tipo_documento', sa.VARCHAR(length=50), nullable=True),
    sa.Column('fecha_carga', sa.DATETIME(), nullable=True),
    sa.ForeignKeyConstraint(['activo_id'], ['activos.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('documentos_activos', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_documentos_activos_id'), ['id'], unique=False)

    op.create_table('documentos_licencias',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('licencia_id', sa.INTEGER(), nullable=False),
    sa.Column('nombre_archivo', sa.VARCHAR(length=255), nullable=False),
    sa.Column('ruta_archivo', sa.VARCHAR(length=500), nullable=False),
    sa.Column('tipo_documento', sa.VARCHAR(length=50), nullable=True),
    sa.Column('fecha_carga', sa.DATETIME(), nullable=True),
    sa.ForeignKeyConstraint(['licencia_id'], ['licencias.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('documentos_licencias', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_documentos_licencias_id'), ['id'], unique=False)

    # ### end Alembic commands ###
