"""add_working_hours_final_v3

Revision ID: 15b40498e1a0
Revises: 22f9e29c5327
Create Date: 2026-06-15 15:22:52.177188

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '15b40498e1a0'
down_revision: Union[str, Sequence[str], None] = '22f9e29c5327'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('horarios_laborales',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('usuario_id', sa.Integer(), nullable=False),
    sa.Column('dia_semana', sa.Integer(), nullable=False),
    sa.Column('es_laboral', sa.Boolean(), nullable=True),
    sa.Column('hora_inicio_1', sa.String(length=5), nullable=True),
    sa.Column('hora_fin_1', sa.String(length=5), nullable=True),
    sa.Column('hora_inicio_2', sa.String(length=5), nullable=True),
    sa.Column('hora_fin_2', sa.String(length=5), nullable=True),
    sa.ForeignKeyConstraint(['usuario_id'], ['usuarios.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('horarios_laborales', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_horarios_laborales_id'), ['id'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('horarios_laborales', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_horarios_laborales_id'))

    op.drop_table('horarios_laborales')
    # ### end Alembic commands ###
