"""Add organizational catalogs and puesto to usuario

Revision ID: 16d58e0f27a9
Revises: 
Create Date: 2026-05-07 15:36:19.378609

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '16d58e0f27a9'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('activos', schema=None) as batch_op:
        batch_op.alter_column('modelo',
               existing_type=sa.TEXT(),
               type_=sa.String(length=100),
               existing_nullable=True)
        batch_op.alter_column('marca_texto',
               existing_type=sa.TEXT(),
               type_=sa.String(length=100),
               existing_nullable=True)
        batch_op.alter_column('imei',
               existing_type=sa.TEXT(),
               type_=sa.String(length=50),
               existing_nullable=True)
        batch_op.alter_column('chip',
               existing_type=sa.TEXT(),
               type_=sa.String(length=50),
               existing_nullable=True)
        batch_op.alter_column('serie',
               existing_type=sa.TEXT(),
               type_=sa.String(length=100),
               existing_nullable=True)
        batch_op.alter_column('ram',
               existing_type=sa.TEXT(),
               type_=sa.String(length=50),
               existing_nullable=True)
        batch_op.alter_column('cpu',
               existing_type=sa.TEXT(),
               type_=sa.String(length=100),
               existing_nullable=True)
        batch_op.alter_column('pulgadas',
               existing_type=sa.TEXT(),
               type_=sa.String(length=50),
               existing_nullable=True)
        batch_op.alter_column('almacenamiento',
               existing_type=sa.TEXT(),
               type_=sa.String(length=100),
               existing_nullable=True)
        batch_op.alter_column('factura_numero',
               existing_type=sa.TEXT(),
               type_=sa.String(length=100),
               existing_nullable=True)
        batch_op.create_foreign_key('fk_activos_marcas', 'marcas', ['marca_id'], ['id'])
        batch_op.create_foreign_key('fk_activos_proveedores', 'proveedores', ['proveedor_id'], ['id'])
        batch_op.drop_column('marca')

    with op.batch_alter_table('comentarios', schema=None) as batch_op:
        batch_op.alter_column('adjunto_url',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               existing_nullable=True)
        batch_op.alter_column('adjunto_nombre',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               existing_nullable=True)

    with op.batch_alter_table('licencias', schema=None) as batch_op:
        batch_op.alter_column('proveedor_texto',
               existing_type=sa.TEXT(),
               type_=sa.String(length=100),
               existing_nullable=True)
        batch_op.alter_column('estatus',
               existing_type=sa.TEXT(),
               type_=sa.Enum('Activa', 'Vencida', 'Cancelada', 'Baja', name='estatuslicencia'),
               existing_nullable=True,
               existing_server_default=sa.text("'Activa'"))
        batch_op.create_foreign_key('fk_licencias_proveedores', 'proveedores', ['proveedor_id'], ['id'])
        batch_op.drop_column('proveedor')

    with op.batch_alter_table('usuarios', schema=None) as batch_op:
        batch_op.add_column(sa.Column('puesto', sa.String(length=100), nullable=True))
        batch_op.alter_column('avatar_url',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               existing_nullable=True)
        batch_op.alter_column('horario_entrada',
               existing_type=sa.TEXT(),
               type_=sa.String(length=5),
               existing_nullable=True,
               existing_server_default=sa.text("'09:00'"))
        batch_op.alter_column('horario_salida',
               existing_type=sa.TEXT(),
               type_=sa.String(length=5),
               existing_nullable=True,
               existing_server_default=sa.text("'18:00'"))

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('usuarios', schema=None) as batch_op:
        batch_op.alter_column('horario_salida',
               existing_type=sa.String(length=5),
               type_=sa.TEXT(),
               existing_nullable=True,
               existing_server_default=sa.text("'18:00'"))
        batch_op.alter_column('horario_entrada',
               existing_type=sa.String(length=5),
               type_=sa.TEXT(),
               existing_nullable=True,
               existing_server_default=sa.text("'09:00'"))
        batch_op.alter_column('avatar_url',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               existing_nullable=True)
        batch_op.drop_column('puesto')

    with op.batch_alter_table('licencias', schema=None) as batch_op:
        batch_op.add_column(sa.Column('proveedor', sa.VARCHAR(length=100), nullable=False))
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.alter_column('estatus',
               existing_type=sa.Enum('Activa', 'Vencida', 'Cancelada', 'Baja', name='estatuslicencia'),
               type_=sa.TEXT(),
               existing_nullable=True,
               existing_server_default=sa.text("'Activa'"))
        batch_op.alter_column('proveedor_texto',
               existing_type=sa.String(length=100),
               type_=sa.TEXT(),
               existing_nullable=True)

    with op.batch_alter_table('comentarios', schema=None) as batch_op:
        batch_op.alter_column('adjunto_nombre',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               existing_nullable=True)
        batch_op.alter_column('adjunto_url',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               existing_nullable=True)

    with op.batch_alter_table('activos', schema=None) as batch_op:
        batch_op.add_column(sa.Column('marca', sa.VARCHAR(length=100), nullable=True))
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.alter_column('factura_numero',
               existing_type=sa.String(length=100),
               type_=sa.TEXT(),
               existing_nullable=True)
        batch_op.alter_column('almacenamiento',
               existing_type=sa.String(length=100),
               type_=sa.TEXT(),
               existing_nullable=True)
        batch_op.alter_column('pulgadas',
               existing_type=sa.String(length=50),
               type_=sa.TEXT(),
               existing_nullable=True)
        batch_op.alter_column('cpu',
               existing_type=sa.String(length=100),
               type_=sa.TEXT(),
               existing_nullable=True)
        batch_op.alter_column('ram',
               existing_type=sa.String(length=50),
               type_=sa.TEXT(),
               existing_nullable=True)
        batch_op.alter_column('serie',
               existing_type=sa.String(length=100),
               type_=sa.TEXT(),
               existing_nullable=True)
        batch_op.alter_column('chip',
               existing_type=sa.String(length=50),
               type_=sa.TEXT(),
               existing_nullable=True)
        batch_op.alter_column('imei',
               existing_type=sa.String(length=50),
               type_=sa.TEXT(),
               existing_nullable=True)
        batch_op.alter_column('marca_texto',
               existing_type=sa.String(length=100),
               type_=sa.TEXT(),
               existing_nullable=True)
        batch_op.alter_column('modelo',
               existing_type=sa.String(length=100),
               type_=sa.TEXT(),
               existing_nullable=True)

    # ### end Alembic commands ###
