"""add especificaciones_json to modelo_parte

Revision ID: 31ac48704cd8
Revises: 4fff5099c5e9
Create Date: 2026-06-15 15:44:39.249825

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '31ac48704cd8'
down_revision: Union[str, Sequence[str], None] = '4fff5099c5e9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('modelo_partes', schema=None) as batch_op:
        batch_op.add_column(sa.Column('especificaciones_json', sa.JSON(), nullable=True))

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('modelo_partes', schema=None) as batch_op:
        batch_op.drop_column('especificaciones_json')

    # ### end Alembic commands ###
