"""zen_it_arquitectura_completa


Revision ID: 3dc9b45a1b8b
Revises: b0985078d43b
Create Date: 2026-04-01 13:49:09.696329

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3dc9b45a1b8b'
down_revision: Union[str, Sequence[str], None] = 'b0985078d43b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('activos', sa.Column('etiqueta_gnn', sa.String(), nullable=True))
    op.add_column('activos', sa.Column('nombre', sa.String(), nullable=True))
    op.add_column('activos', sa.Column('serie', sa.String(), nullable=True))
    op.add_column('activos', sa.Column('categoria', sa.String(), nullable=True))
    op.add_column('activos', sa.Column('marca_id', sa.Integer(), nullable=True))
    op.add_column('activos', sa.Column('proveedor_id', sa.Integer(), nullable=True))
    op.add_column('activos', sa.Column('usuario_id', sa.Integer(), nullable=True))
    op.add_column('activos', sa.Column('status', sa.String(), nullable=True))
    op.add_column('activos', sa.Column('factura_url', sa.String(), nullable=True))
    op.add_column('activos', sa.Column('responsiva_url', sa.String(), nullable=True))
    op.add_column('activos', sa.Column('is_deleted', sa.Boolean(), nullable=True))
    op.add_column('activos', sa.Column('deleted_at', sa.DateTime(), nullable=True))
    op.drop_index(op.f('ix_activos_numero_serie'), table_name='activos')
    op.create_index(op.f('ix_activos_etiqueta_gnn'), 'activos', ['etiqueta_gnn'], unique=True)
    op.drop_constraint(None, 'activos', type_='foreignkey')
    op.create_foreign_key(None, 'activos', 'usuarios', ['usuario_id'], ['id'])
    op.create_foreign_key(None, 'activos', 'marcas', ['marca_id'], ['id'])
    op.create_foreign_key(None, 'activos', 'proveedores', ['proveedor_id'], ['id'])
    op.drop_column('activos', 'numero_serie')
    op.drop_column('activos', 'estatus_operativo')
    op.drop_column('activos', 'proveedor')
    op.drop_column('activos', 'created_at')
    op.drop_column('activos', 'usuario_asignado_id')
    op.drop_column('activos', 'costo')
    op.drop_column('activos', 'updated_at')
    op.drop_column('activos', 'modelo')
    op.drop_column('activos', 'marca')
    op.drop_column('activos', 'is_active')
    op.add_column('tickets', sa.Column('prioridad', sa.Enum('CRITICA', 'ALTA', 'MEDIA', 'BAJA', name='prioridadsla'), nullable=True))
    op.add_column('tickets', sa.Column('status', sa.Enum('ABIERTO', 'EN_PROGRESO', 'ESPERA_USUARIO', 'CERRADO', 'CANCELADO', name='statusticket'), nullable=True))
    op.add_column('tickets', sa.Column('fecha_creacion', sa.DateTime(), nullable=True))
    op.add_column('tickets', sa.Column('fecha_vencimiento_sla', sa.DateTime(), nullable=True))
    op.add_column('tickets', sa.Column('fecha_cierre', sa.DateTime(), nullable=True))
    op.add_column('tickets', sa.Column('imagen_referencia_url', sa.String(), nullable=True))
    op.add_column('tickets', sa.Column('creador_id', sa.Integer(), nullable=True))
    op.alter_column('tickets', 'titulo',
               existing_type=sa.VARCHAR(length=200),
               nullable=True)
    op.alter_column('tickets', 'descripcion',
               existing_type=sa.TEXT(),
               nullable=True)
    op.create_index(op.f('ix_tickets_titulo'), 'tickets', ['titulo'], unique=False)
    op.drop_constraint(None, 'tickets', type_='foreignkey')
    op.create_foreign_key(None, 'tickets', 'usuarios', ['creador_id'], ['id'])
    op.drop_column('tickets', 'usuario_id')
    op.drop_column('tickets', 'estatus')
    op.drop_column('tickets', 'created_at')
    op.drop_column('tickets', 'sla_prioridad')
    op.drop_column('tickets', 'updated_at')
    op.drop_column('tickets', 'is_active')
    op.add_column('usuarios', sa.Column('status_tecnico', sa.Enum('ACTIVO', 'OCUPADO', 'VACACIONES', 'COMIENDO', 'FUERA', name='statustecnico'), nullable=True))
    op.add_column('usuarios', sa.Column('foto_perfil', sa.String(), nullable=True))
    op.add_column('usuarios', sa.Column('is_deleted', sa.Boolean(), nullable=True))
    op.add_column('usuarios', sa.Column('deleted_at', sa.DateTime(), nullable=True))
    op.alter_column('usuarios', 'nombre',
               existing_type=sa.VARCHAR(length=100),
               nullable=True)
    op.alter_column('usuarios', 'email',
               existing_type=sa.VARCHAR(length=100),
               nullable=True)
    op.alter_column('usuarios', 'hashed_password',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('usuarios', 'rol',
               existing_type=sa.VARCHAR(length=20),
               type_=sa.Enum('ADMIN', 'TECNICO', 'NORMAL', name='rolusuario'),
               existing_nullable=True)
    op.create_index(op.f('ix_usuarios_nombre'), 'usuarios', ['nombre'], unique=False)
    op.drop_constraint(None, 'usuarios', type_='foreignkey')
    op.drop_column('usuarios', 'created_at')
    op.drop_column('usuarios', 'status')
    op.drop_column('usuarios', 'tecnico_preferente_id')
    op.drop_column('usuarios', 'updated_at')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('usuarios', sa.Column('updated_at', sa.DATETIME(), nullable=True))
    op.add_column('usuarios', sa.Column('tecnico_preferente_id', sa.INTEGER(), nullable=True))
    op.add_column('usuarios', sa.Column('status', sa.VARCHAR(length=20), nullable=True))
    op.add_column('usuarios', sa.Column('created_at', sa.DATETIME(), nullable=True))
    op.create_foreign_key(None, 'usuarios', 'usuarios', ['tecnico_preferente_id'], ['id'])
    op.drop_index(op.f('ix_usuarios_nombre'), table_name='usuarios')
    op.alter_column('usuarios', 'rol',
               existing_type=sa.Enum('ADMIN', 'TECNICO', 'NORMAL', name='rolusuario'),
               type_=sa.VARCHAR(length=20),
               existing_nullable=True)
    op.alter_column('usuarios', 'hashed_password',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('usuarios', 'email',
               existing_type=sa.VARCHAR(length=100),
               nullable=False)
    op.alter_column('usuarios', 'nombre',
               existing_type=sa.VARCHAR(length=100),
               nullable=False)
    op.drop_column('usuarios', 'deleted_at')
    op.drop_column('usuarios', 'is_deleted')
    op.drop_column('usuarios', 'foto_perfil')
    op.drop_column('usuarios', 'status_tecnico')
    op.add_column('tickets', sa.Column('is_active', sa.BOOLEAN(), nullable=True))
    op.add_column('tickets', sa.Column('updated_at', sa.DATETIME(), nullable=True))
    op.add_column('tickets', sa.Column('sla_prioridad', sa.VARCHAR(length=20), nullable=False))
    op.add_column('tickets', sa.Column('created_at', sa.DATETIME(), nullable=True))
    op.add_column('tickets', sa.Column('estatus', sa.VARCHAR(length=20), nullable=True))
    op.add_column('tickets', sa.Column('usuario_id', sa.INTEGER(), nullable=False))
    op.drop_constraint(None, 'tickets', type_='foreignkey')
    op.create_foreign_key(None, 'tickets', 'usuarios', ['usuario_id'], ['id'])
    op.drop_index(op.f('ix_tickets_titulo'), table_name='tickets')
    op.alter_column('tickets', 'descripcion',
               existing_type=sa.TEXT(),
               nullable=False)
    op.alter_column('tickets', 'titulo',
               existing_type=sa.VARCHAR(length=200),
               nullable=False)
    op.drop_column('tickets', 'creador_id')
    op.drop_column('tickets', 'imagen_referencia_url')
    op.drop_column('tickets', 'fecha_cierre')
    op.drop_column('tickets', 'fecha_vencimiento_sla')
    op.drop_column('tickets', 'fecha_creacion')
    op.drop_column('tickets', 'status')
    op.drop_column('tickets', 'prioridad')
    op.add_column('activos', sa.Column('is_active', sa.BOOLEAN(), nullable=True))
    op.add_column('activos', sa.Column('marca', sa.VARCHAR(length=100), nullable=True))
    op.add_column('activos', sa.Column('modelo', sa.VARCHAR(length=150), nullable=True))
    op.add_column('activos', sa.Column('updated_at', sa.DATETIME(), nullable=True))
    op.add_column('activos', sa.Column('costo', sa.FLOAT(), nullable=True))
    op.add_column('activos', sa.Column('usuario_asignado_id', sa.INTEGER(), nullable=True))
    op.add_column('activos', sa.Column('created_at', sa.DATETIME(), nullable=True))
    op.add_column('activos', sa.Column('proveedor', sa.VARCHAR(length=100), nullable=True))
    op.add_column('activos', sa.Column('estatus_operativo', sa.VARCHAR(length=50), nullable=True))
    op.add_column('activos', sa.Column('numero_serie', sa.VARCHAR(length=100), nullable=True))
    op.drop_constraint(None, 'activos', type_='foreignkey')
    op.drop_constraint(None, 'activos', type_='foreignkey')
    op.drop_constraint(None, 'activos', type_='foreignkey')
    op.create_foreign_key(None, 'activos', 'usuarios', ['usuario_asignado_id'], ['id'])
    op.drop_index(op.f('ix_activos_etiqueta_gnn'), table_name='activos')
    op.create_index(op.f('ix_activos_numero_serie'), 'activos', ['numero_serie'], unique=1)
    op.drop_column('activos', 'deleted_at')
    op.drop_column('activos', 'is_deleted')
    op.drop_column('activos', 'responsiva_url')
    op.drop_column('activos', 'factura_url')
    op.drop_column('activos', 'status')
    op.drop_column('activos', 'usuario_id')
    op.drop_column('activos', 'proveedor_id')
    op.drop_column('activos', 'marca_id')
    op.drop_column('activos', 'categoria')
    op.drop_column('activos', 'serie')
    op.drop_column('activos', 'nombre')
    op.drop_column('activos', 'etiqueta_gnn')
    # ### end Alembic commands ###
