"""add part number catalog v2

Revision ID: 4fff5099c5e9
Revises: 15b40498e1a0
Create Date: 2026-06-15 15:35:11.268487

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4fff5099c5e9'
down_revision: Union[str, Sequence[str], None] = '15b40498e1a0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('modelo_partes',
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('numero_parte', sa.String(length=100), nullable=False),
        sa.Column('nombre', sa.String(length=150), nullable=False),
        sa.Column('descripcion', sa.String(length=500), nullable=True),
        sa.Column('marca_id', sa.Integer(), nullable=True),
        sa.Column('tipo', sa.String(length=100), nullable=True),
        sa.Column('ram', sa.String(length=50), nullable=True),
        sa.Column('cpu', sa.String(length=100), nullable=True),
        sa.Column('almacenamiento', sa.String(length=50), nullable=True),
        sa.Column('pulgadas', sa.String(length=20), nullable=True),
        sa.Column('rma', sa.String(length=100), nullable=True),
        sa.ForeignKeyConstraint(['marca_id'], ['marcas.id'], name='fk_modelo_partes_marca_id'),
        sa.PrimaryKeyConstraint('id', name='pk_modelo_partes')
    )
    with op.batch_alter_table('modelo_partes', schema=None) as batch_op:
        batch_op.create_index('ix_modelo_partes_id', ['id'], unique=False)
        batch_op.create_index('ix_modelo_partes_numero_parte', ['numero_parte'], unique=True)

    with op.batch_alter_table('activos', schema=None) as batch_op:
        batch_op.add_column(sa.Column('numero_parte', sa.String(length=100), nullable=True))
        batch_op.add_column(sa.Column('modelo_parte_id', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('rma', sa.String(length=100), nullable=True))
        batch_op.create_index('ix_activos_numero_parte', ['numero_parte'], unique=False)
        batch_op.create_foreign_key('fk_activos_modelo_parte_id', 'modelo_partes', ['modelo_parte_id'], ['id'])

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('activos', schema=None) as batch_op:
        batch_op.drop_constraint('fk_activos_modelo_parte_id', type_='foreignkey')
        batch_op.drop_index('ix_activos_numero_parte')
        batch_op.drop_column('rma')
        batch_op.drop_column('modelo_parte_id')
        batch_op.drop_column('numero_parte')

    op.drop_table('modelo_partes')
    # ### end Alembic commands ###
