"""add_categoria_is_signed_to_documento

Revision ID: 524f764c72cb
Revises: 974b25eb33ee
Create Date: 2026-07-17 15:46:28.171235

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '524f764c72cb'
down_revision: Union[str, Sequence[str], None] = '974b25eb33ee'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    conn = op.get_bind()
    inspector = sa.inspect(conn)
    
    # Comprobar si la tabla existe antes de inspeccionar índices
    if 'documentos_activos' in inspector.get_table_names():
        existing_indexes = [i['name'] for i in inspector.get_indexes('documentos_activos')]
        if 'ix_documentos_activos_id' in existing_indexes:
            with op.batch_alter_table('documentos_activos', schema=None) as batch_op:
                batch_op.drop_index(batch_op.f('ix_documentos_activos_id'))
        op.drop_table('documentos_activos')
    
    # Comprobar si la tabla existe antes de inspeccionar índices
    if 'documentos_licencias' in inspector.get_table_names():
        existing_indexes = [i['name'] for i in inspector.get_indexes('documentos_licencias')]
        if 'ix_documentos_licencias_id' in existing_indexes:
            with op.batch_alter_table('documentos_licencias', schema=None) as batch_op:
                batch_op.drop_index(batch_op.f('ix_documentos_licencias_id'))
        op.drop_table('documentos_licencias')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('documentos_licencias',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('licencia_id', sa.INTEGER(), nullable=False),
    sa.Column('nombre_archivo', sa.VARCHAR(length=255), nullable=False),
    sa.Column('ruta_archivo', sa.VARCHAR(length=500), nullable=False),
    sa.Column('tipo_documento', sa.VARCHAR(length=50), nullable=True),
    sa.Column('fecha_carga', sa.DATETIME(), nullable=True),
    sa.ForeignKeyConstraint(['licencia_id'], ['licencias.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('documentos_licencias', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_documentos_licencias_id'), ['id'], unique=False)

    op.create_table('documentos_activos',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('activo_id', sa.INTEGER(), nullable=False),
    sa.Column('nombre_archivo', sa.VARCHAR(length=255), nullable=False),
    sa.Column('ruta_archivo', sa.VARCHAR(length=500), nullable=False),
    sa.Column('tipo_documento', sa.VARCHAR(length=50), nullable=True),
    sa.Column('fecha_carga', sa.DATETIME(), nullable=True),
    sa.ForeignKeyConstraint(['activo_id'], ['activos.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('documentos_activos', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_documentos_activos_id'), ['id'], unique=False)

    # ### end Alembic commands ###
