"""add_firma_resguardo_to_activo

Revision ID: 5dbd17a4b735
Revises: 524f764c72cb
Create Date: 2026-07-28 10:58:10.703957

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5dbd17a4b735'
down_revision: Union[str, Sequence[str], None] = '524f764c72cb'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('activos', schema=None) as batch_op:
        batch_op.add_column(sa.Column('firma_resguardo', sa.String(), nullable=True))

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('activos', schema=None) as batch_op:
        batch_op.drop_column('firma_resguardo')

    # ### end Alembic commands ###
