"""initial_schema_with_documento_model

Revision ID: 70b70a80622c
Revises: 
Create Date: 2026-06-25 12:55:16.830473

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '70b70a80622c'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('auditoria',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('usuario_id', sa.Integer(), nullable=True),
    sa.Column('accion', sa.String(), nullable=True),
    sa.Column('tabla_afectada', sa.String(), nullable=True),
    sa.Column('registro_id', sa.Integer(), nullable=True),
    sa.Column('detalles_previos', sa.JSON(), nullable=True),
    sa.Column('detalles_nuevos', sa.JSON(), nullable=True),
    sa.Column('fecha', sa.DateTime(), nullable=True),
    sa.Column('ip_origen', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('auditoria', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_auditoria_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_auditoria_usuario_id'), ['usuario_id'], unique=False)

    op.create_table('categorias_activos',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nombre', sa.String(length=100), nullable=False),
    sa.Column('icono', sa.String(length=50), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('categorias_activos', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_categorias_activos_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_categorias_activos_nombre'), ['nombre'], unique=True)

    op.create_table('centros_costo',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('codigo', sa.String(length=50), nullable=False),
    sa.Column('nombre', sa.String(length=100), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('centros_costo', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_centros_costo_codigo'), ['codigo'], unique=True)
        batch_op.create_index(batch_op.f('ix_centros_costo_id'), ['id'], unique=False)

    op.create_table('configuracion_smtp',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('smtp_host', sa.String(length=255), nullable=True),
    sa.Column('smtp_port', sa.Integer(), nullable=True),
    sa.Column('smtp_user', sa.String(length=255), nullable=True),
    sa.Column('smtp_password', sa.String(length=255), nullable=True),
    sa.Column('smtp_tls', sa.Boolean(), nullable=True),
    sa.Column('emails_from_email', sa.String(length=255), nullable=True),
    sa.Column('emails_from_name', sa.String(length=255), nullable=True),
    sa.Column('notificar_ticket_creado', sa.Boolean(), nullable=True),
    sa.Column('notificar_ticket_reasignado', sa.Boolean(), nullable=True),
    sa.Column('notificar_ticket_cerrado', sa.Boolean(), nullable=True),
    sa.Column('notificar_activo_asignado', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('configuracion_smtp', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_configuracion_smtp_id'), ['id'], unique=False)

    op.create_table('marcas',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nombre', sa.String(length=100), nullable=False),
    sa.Column('descripcion', sa.String(length=255), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('marcas', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_marcas_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_marcas_nombre'), ['nombre'], unique=True)

    op.create_table('proveedores',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nombre', sa.String(length=150), nullable=False),
    sa.Column('rfc', sa.String(length=20), nullable=True),
    sa.Column('contacto_nombre', sa.String(length=150), nullable=True),
    sa.Column('contacto_telefono', sa.String(length=50), nullable=True),
    sa.Column('contacto_email', sa.String(length=150), nullable=True),
    sa.Column('notas', sa.String(length=500), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('proveedores', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_proveedores_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_proveedores_nombre'), ['nombre'], unique=True)

    op.create_table('puestos',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nombre', sa.String(length=150), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('puestos', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_puestos_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_puestos_nombre'), ['nombre'], unique=True)

    op.create_table('sla_configs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('prioridad', sa.String(length=50), nullable=False),
    sa.Column('horas', sa.Integer(), nullable=False),
    sa.Column('descripcion', sa.String(length=255), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('sla_configs', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_sla_configs_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_sla_configs_prioridad'), ['prioridad'], unique=True)

    op.create_table('usuarios',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nombre_completo', sa.String(length=100), nullable=False),
    sa.Column('email', sa.String(length=100), nullable=False),
    sa.Column('hashed_password', sa.String(), nullable=False),
    sa.Column('rol', sa.Enum('Admin', 'Tecnico', 'Especialista', 'Usuario', name='rolusuario'), nullable=True),
    sa.Column('zona', sa.String(length=50), nullable=True),
    sa.Column('departamento', sa.String(length=50), nullable=True),
    sa.Column('centro_costo', sa.String(length=50), nullable=True),
    sa.Column('empresa', sa.String(length=100), nullable=True),
    sa.Column('no_empleado', sa.String(length=50), nullable=True),
    sa.Column('fecha_ingreso', sa.DateTime(), nullable=True),
    sa.Column('subdepartamento', sa.String(length=100), nullable=True),
    sa.Column('puesto', sa.String(length=100), nullable=True),
    sa.Column('proyecto', sa.String(length=100), nullable=True),
    sa.Column('ciudad', sa.String(length=100), nullable=True),
    sa.Column('estado', sa.String(length=100), nullable=True),
    sa.Column('razon_social', sa.String(length=200), nullable=True),
    sa.Column('registro_patronal', sa.String(length=100), nullable=True),
    sa.Column('razon_social_pagadora', sa.String(length=200), nullable=True),
    sa.Column('no_banca', sa.String(length=100), nullable=True),
    sa.Column('banco_pagador', sa.String(length=100), nullable=True),
    sa.Column('correo_personal', sa.String(length=100), nullable=True),
    sa.Column('celular_personal', sa.String(length=20), nullable=True),
    sa.Column('celular_red', sa.String(length=20), nullable=True),
    sa.Column('imss', sa.String(length=50), nullable=True),
    sa.Column('rfc', sa.String(length=20), nullable=True),
    sa.Column('curp', sa.String(length=20), nullable=True),
    sa.Column('fecha_nacimiento', sa.DateTime(), nullable=True),
    sa.Column('edad', sa.Integer(), nullable=True),
    sa.Column('sexo', sa.String(length=20), nullable=True),
    sa.Column('estatus', sa.Enum('Activo', 'Inactivo', name='estatususuario'), nullable=True),
    sa.Column('ausente', sa.Boolean(), nullable=True),
    sa.Column('avatar_url', sa.String(length=255), nullable=True),
    sa.Column('tecnico_principal_id', sa.Integer(), nullable=True),
    sa.Column('tecnico_secundario_id', sa.Integer(), nullable=True),
    sa.Column('is_tecnico_principal', sa.Boolean(), nullable=True),
    sa.Column('status_tecnico', sa.Enum('Activo', 'Ocupado', 'Comiendo', 'Ausente', 'Fuera_de_Oficina', 'Vacaciones', name='statustecnico'), nullable=True),
    sa.Column('especialidad', sa.String(length=100), nullable=True),
    sa.Column('debe_cambiar_password', sa.Boolean(), nullable=True),
    sa.Column('is_email_verified', sa.Boolean(), nullable=True),
    sa.Column('email_verification_token', sa.String(length=100), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('fecha_creacion', sa.DateTime(), nullable=True),
    sa.Column('fecha_actualizacion', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['tecnico_principal_id'], ['usuarios.id'], ),
    sa.ForeignKeyConstraint(['tecnico_secundario_id'], ['usuarios.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('usuarios', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_usuarios_email'), ['email'], unique=True)
        batch_op.create_index(batch_op.f('ix_usuarios_id'), ['id'], unique=False)

    op.create_table('zonas',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nombre', sa.String(length=100), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('zonas', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_zonas_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_zonas_nombre'), ['nombre'], unique=True)

    op.create_table('articulos',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('vistas', sa.Integer(), nullable=True),
    sa.Column('fecha_creacion', sa.DateTime(), nullable=True),
    sa.Column('titulo', sa.String(length=200), nullable=False),
    sa.Column('categoria', sa.String(length=100), nullable=False),
    sa.Column('visibilidad', sa.Enum('Externo', 'Interno', name='visibilidadarticulo'), nullable=True),
    sa.Column('imagenUrl', sa.String(), nullable=True),
    sa.Column('contenido', sa.Text(), nullable=False),
    sa.Column('autor_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['autor_id'], ['usuarios.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('articulos', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_articulos_id'), ['id'], unique=False)

    op.create_table('departamentos',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nombre', sa.String(length=100), nullable=False),
    sa.Column('zona_id', sa.Integer(), nullable=True),
    sa.Column('centro_costo_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['centro_costo_id'], ['centros_costo.id'], ),
    sa.ForeignKeyConstraint(['zona_id'], ['zonas.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('departamentos', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_departamentos_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_departamentos_nombre'), ['nombre'], unique=False)

    op.create_table('historial_status_tecnicos',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('tecnico_id', sa.Integer(), nullable=False),
    sa.Column('status_anterior', sa.String(length=50), nullable=True),
    sa.Column('status_nuevo', sa.String(length=50), nullable=True),
    sa.Column('fecha_cambio', sa.DateTime(), nullable=True),
    sa.Column('duracion_estimada_minutos', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['tecnico_id'], ['usuarios.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('historial_status_tecnicos', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_historial_status_tecnicos_id'), ['id'], unique=False)

    op.create_table('horarios_laborales',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('usuario_id', sa.Integer(), nullable=False),
    sa.Column('dia_semana', sa.Integer(), nullable=False),
    sa.Column('es_laboral', sa.Boolean(), nullable=True),
    sa.Column('hora_inicio_1', sa.String(length=5), nullable=True),
    sa.Column('hora_fin_1', sa.String(length=5), nullable=True),
    sa.Column('hora_inicio_2', sa.String(length=5), nullable=True),
    sa.Column('hora_fin_2', sa.String(length=5), nullable=True),
    sa.ForeignKeyConstraint(['usuario_id'], ['usuarios.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('horarios_laborales', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_horarios_laborales_id'), ['id'], unique=False)

    op.create_table('licencias',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nombre', sa.String(length=150), nullable=False),
    sa.Column('categoria', sa.String(length=100), nullable=False),
    sa.Column('proveedor_id', sa.Integer(), nullable=True),
    sa.Column('proveedor_texto', sa.String(length=150), nullable=True),
    sa.Column('costo_anual', sa.Float(), nullable=True),
    sa.Column('fecha_compra', sa.Date(), nullable=True),
    sa.Column('fecha_vencimiento', sa.Date(), nullable=True),
    sa.Column('asientos_totales', sa.Integer(), nullable=True),
    sa.Column('llave', sa.String(length=200), nullable=True),
    sa.Column('estatus', sa.String(length=50), nullable=True),
    sa.Column('is_deleted', sa.Boolean(), nullable=True),
    sa.Column('documentos', sa.JSON(), nullable=True),
    sa.Column('asientos_asignados', sa.JSON(), nullable=True),
    sa.Column('historial', sa.JSON(), nullable=True),
    sa.ForeignKeyConstraint(['proveedor_id'], ['proveedores.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('licencias', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_licencias_id'), ['id'], unique=False)

    op.create_table('modelo_partes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('numero_parte', sa.String(length=100), nullable=False),
    sa.Column('nombre', sa.String(length=150), nullable=False),
    sa.Column('descripcion', sa.String(length=500), nullable=True),
    sa.Column('marca_id', sa.Integer(), nullable=True),
    sa.Column('tipo', sa.String(length=100), nullable=True),
    sa.Column('ram', sa.String(length=50), nullable=True),
    sa.Column('cpu', sa.String(length=100), nullable=True),
    sa.Column('almacenamiento', sa.String(length=50), nullable=True),
    sa.Column('pulgadas', sa.String(length=20), nullable=True),
    sa.Column('rma', sa.String(length=100), nullable=True),
    sa.Column('especificaciones_json', sa.JSON(), nullable=True),
    sa.ForeignKeyConstraint(['marca_id'], ['marcas.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('modelo_partes', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_modelo_partes_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_modelo_partes_numero_parte'), ['numero_parte'], unique=True)

    op.create_table('tickets',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('titulo', sa.String(length=200), nullable=False),
    sa.Column('descripcion', sa.Text(), nullable=False),
    sa.Column('prioridad', sa.Enum('Critica', 'Alta', 'Media', 'Baja', name='prioridadticket'), nullable=True),
    sa.Column('estatus', sa.Enum('Abierto', 'En_Progreso', 'En_Espera_Pieza', 'En_Espera_Reunion', 'Resuelto', 'Cerrado', 'Cancelado', 'Escalado_Desarrollo', 'Escalado_Infraestructura', 'Escalado_Redes', name='estatusticket'), nullable=True),
    sa.Column('departamento', sa.String(length=100), nullable=True),
    sa.Column('activo_id', sa.String(length=100), nullable=True),
    sa.Column('fecha_creacion', sa.DateTime(), nullable=True),
    sa.Column('fecha_vencimiento_sla', sa.DateTime(), nullable=True),
    sa.Column('fecha_primera_respuesta', sa.DateTime(), nullable=True),
    sa.Column('fecha_resolucion', sa.DateTime(), nullable=True),
    sa.Column('tiempo_pausado_acumulado', sa.Integer(), nullable=True),
    sa.Column('ultima_fecha_pausa', sa.DateTime(), nullable=True),
    sa.Column('solicitante_id', sa.Integer(), nullable=False),
    sa.Column('tecnico_asignado_id', sa.Integer(), nullable=True),
    sa.Column('satisfaccion_estrellas', sa.Integer(), nullable=True),
    sa.Column('satisfaccion_comentario', sa.Text(), nullable=True),
    sa.Column('reabierto', sa.Boolean(), nullable=True),
    sa.Column('notificado_recordatorio_cierre', sa.Boolean(), nullable=True),
    sa.Column('fecha_actualizacion', sa.DateTime(), nullable=True),
    sa.Column('parent_ticket_id', sa.Integer(), nullable=True),
    sa.Column('is_escalation', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['parent_ticket_id'], ['tickets.id'], ),
    sa.ForeignKeyConstraint(['solicitante_id'], ['usuarios.id'], ),
    sa.ForeignKeyConstraint(['tecnico_asignado_id'], ['usuarios.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('tickets', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_tickets_id'), ['id'], unique=False)

    op.create_table('activos',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('codigo', sa.String(length=50), nullable=False),
    sa.Column('numero_parte', sa.String(length=100), nullable=True),
    sa.Column('modelo_parte_id', sa.Integer(), nullable=True),
    sa.Column('nombre', sa.String(length=150), nullable=False),
    sa.Column('modelo', sa.String(length=100), nullable=True),
    sa.Column('marca_texto', sa.String(length=100), nullable=True),
    sa.Column('marca_id', sa.Integer(), nullable=True),
    sa.Column('proveedor_id', sa.Integer(), nullable=True),
    sa.Column('tipo', sa.Enum('Computo', 'Licencia', 'Periferico', 'Red', 'Celular', name='tipoactivo'), nullable=True),
    sa.Column('estatus', sa.Enum('Asignado', 'Disponible', 'Mantenimiento', 'Baja', 'Obsoleto', 'BajaDefinitiva', name='estatusactivo'), nullable=True),
    sa.Column('motivo_baja', sa.String(length=100), nullable=True),
    sa.Column('fecha_baja', sa.DateTime(), nullable=True),
    sa.Column('imei', sa.String(length=50), nullable=True),
    sa.Column('chip', sa.String(length=50), nullable=True),
    sa.Column('serie', sa.String(length=100), nullable=True),
    sa.Column('ram', sa.String(length=50), nullable=True),
    sa.Column('cpu', sa.String(length=100), nullable=True),
    sa.Column('pulgadas', sa.String(length=20), nullable=True),
    sa.Column('almacenamiento', sa.String(length=50), nullable=True),
    sa.Column('formato', sa.String(length=50), nullable=True),
    sa.Column('rma', sa.String(length=100), nullable=True),
    sa.Column('costo', sa.Float(), nullable=True),
    sa.Column('factura_numero', sa.String(length=100), nullable=True),
    sa.Column('fecha_compra', sa.DateTime(), nullable=True),
    sa.Column('anios_garantia', sa.Integer(), nullable=True),
    sa.Column('fecha_ultimo_mantenimiento', sa.DateTime(), nullable=True),
    sa.Column('meses_mantenimiento', sa.Integer(), nullable=True),
    sa.Column('fecha_proximo_mantenimiento', sa.DateTime(), nullable=True),
    sa.Column('historial', sa.JSON(), nullable=True),
    sa.Column('is_deleted', sa.Integer(), nullable=True),
    sa.Column('usuario_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['marca_id'], ['marcas.id'], ),
    sa.ForeignKeyConstraint(['modelo_parte_id'], ['modelo_partes.id'], ),
    sa.ForeignKeyConstraint(['proveedor_id'], ['proveedores.id'], ),
    sa.ForeignKeyConstraint(['usuario_id'], ['usuarios.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('activos', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_activos_codigo'), ['codigo'], unique=True)
        batch_op.create_index(batch_op.f('ix_activos_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_activos_numero_parte'), ['numero_parte'], unique=False)

    op.create_table('comentarios',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('ticket_id', sa.Integer(), nullable=True),
    sa.Column('autor_id', sa.Integer(), nullable=True),
    sa.Column('texto', sa.Text(), nullable=False),
    sa.Column('fecha', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['autor_id'], ['usuarios.id'], ),
    sa.ForeignKeyConstraint(['ticket_id'], ['tickets.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('comentarios', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_comentarios_id'), ['id'], unique=False)

    op.create_table('ticket_timeline',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('ticket_id', sa.Integer(), nullable=False),
    sa.Column('evento', sa.String(length=100), nullable=True),
    sa.Column('descripcion', sa.Text(), nullable=True),
    sa.Column('icon', sa.String(length=50), nullable=True),
    sa.Column('color', sa.String(length=20), nullable=True),
    sa.Column('fecha', sa.DateTime(), nullable=True),
    sa.Column('metadata_extra', sa.JSON(), nullable=True),
    sa.ForeignKeyConstraint(['ticket_id'], ['tickets.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('ticket_timeline', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_ticket_timeline_id'), ['id'], unique=False)

    op.create_table('usuario_licencia',
    sa.Column('usuario_id', sa.Integer(), nullable=False),
    sa.Column('licencia_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['licencia_id'], ['licencias.id'], ),
    sa.ForeignKeyConstraint(['usuario_id'], ['usuarios.id'], ),
    sa.PrimaryKeyConstraint('usuario_id', 'licencia_id')
    )
    op.create_table('activo_licencia',
    sa.Column('activo_id', sa.Integer(), nullable=False),
    sa.Column('licencia_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['activo_id'], ['activos.id'], ),
    sa.ForeignKeyConstraint(['licencia_id'], ['licencias.id'], ),
    sa.PrimaryKeyConstraint('activo_id', 'licencia_id')
    )
    op.create_table('mantenimientos',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('activo_id', sa.Integer(), nullable=False),
    sa.Column('tecnico_id', sa.Integer(), nullable=True),
    sa.Column('fecha', sa.DateTime(), nullable=True),
    sa.Column('tipo', sa.String(length=50), nullable=True),
    sa.Column('descripcion', sa.String(length=500), nullable=True),
    sa.Column('costo', sa.Float(), nullable=True),
    sa.Column('notas_internas', sa.String(length=500), nullable=True),
    sa.ForeignKeyConstraint(['activo_id'], ['activos.id'], ),
    sa.ForeignKeyConstraint(['tecnico_id'], ['usuarios.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('mantenimientos', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_mantenimientos_id'), ['id'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('mantenimientos', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_mantenimientos_id'))

    op.drop_table('mantenimientos')
    op.drop_table('activo_licencia')
    op.drop_table('usuario_licencia')
    with op.batch_alter_table('ticket_timeline', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_ticket_timeline_id'))

    op.drop_table('ticket_timeline')
    with op.batch_alter_table('comentarios', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_comentarios_id'))

    op.drop_table('comentarios')
    with op.batch_alter_table('activos', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_activos_numero_parte'))
        batch_op.drop_index(batch_op.f('ix_activos_id'))
        batch_op.drop_index(batch_op.f('ix_activos_codigo'))

    op.drop_table('activos')
    with op.batch_alter_table('tickets', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_tickets_id'))

    op.drop_table('tickets')
    with op.batch_alter_table('modelo_partes', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_modelo_partes_numero_parte'))
        batch_op.drop_index(batch_op.f('ix_modelo_partes_id'))

    op.drop_table('modelo_partes')
    with op.batch_alter_table('licencias', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_licencias_id'))

    op.drop_table('licencias')
    with op.batch_alter_table('horarios_laborales', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_horarios_laborales_id'))

    op.drop_table('horarios_laborales')
    with op.batch_alter_table('historial_status_tecnicos', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_historial_status_tecnicos_id'))

    op.drop_table('historial_status_tecnicos')
    with op.batch_alter_table('departamentos', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_departamentos_nombre'))
        batch_op.drop_index(batch_op.f('ix_departamentos_id'))

    op.drop_table('departamentos')
    with op.batch_alter_table('articulos', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_articulos_id'))

    op.drop_table('articulos')
    with op.batch_alter_table('zonas', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_zonas_nombre'))
        batch_op.drop_index(batch_op.f('ix_zonas_id'))

    op.drop_table('zonas')
    with op.batch_alter_table('usuarios', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_usuarios_id'))
        batch_op.drop_index(batch_op.f('ix_usuarios_email'))

    op.drop_table('usuarios')
    with op.batch_alter_table('sla_configs', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_sla_configs_prioridad'))
        batch_op.drop_index(batch_op.f('ix_sla_configs_id'))

    op.drop_table('sla_configs')
    with op.batch_alter_table('puestos', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_puestos_nombre'))
        batch_op.drop_index(batch_op.f('ix_puestos_id'))

    op.drop_table('puestos')
    with op.batch_alter_table('proveedores', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_proveedores_nombre'))
        batch_op.drop_index(batch_op.f('ix_proveedores_id'))

    op.drop_table('proveedores')
    with op.batch_alter_table('marcas', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_marcas_nombre'))
        batch_op.drop_index(batch_op.f('ix_marcas_id'))

    op.drop_table('marcas')
    with op.batch_alter_table('configuracion_smtp', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_configuracion_smtp_id'))

    op.drop_table('configuracion_smtp')
    with op.batch_alter_table('centros_costo', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_centros_costo_id'))
        batch_op.drop_index(batch_op.f('ix_centros_costo_codigo'))

    op.drop_table('centros_costo')
    with op.batch_alter_table('categorias_activos', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_categorias_activos_nombre'))
        batch_op.drop_index(batch_op.f('ix_categorias_activos_id'))

    op.drop_table('categorias_activos')
    with op.batch_alter_table('auditoria', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_auditoria_usuario_id'))
        batch_op.drop_index(batch_op.f('ix_auditoria_id'))

    op.drop_table('auditoria')
    # ### end Alembic commands ###
