"""add_asignacion_tecnica_model

Revision ID: 974b25eb33ee
Revises: da490a75f45b
Create Date: 2026-07-14 15:59:52.588785

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '974b25eb33ee'
down_revision: Union[str, Sequence[str], None] = 'da490a75f45b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('asignaciones_tecnicas',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('zona_id', sa.Integer(), nullable=False),
    sa.Column('departamento_id', sa.Integer(), nullable=False),
    sa.Column('tecnico_principal_id', sa.Integer(), nullable=False),
    sa.Column('tecnico_secundario_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['departamento_id'], ['departamentos.id'], ),
    sa.ForeignKeyConstraint(['tecnico_principal_id'], ['usuarios.id'], ),
    sa.ForeignKeyConstraint(['tecnico_secundario_id'], ['usuarios.id'], ),
    sa.ForeignKeyConstraint(['zona_id'], ['zonas.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('asignaciones_tecnicas', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_asignaciones_tecnicas_id'), ['id'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('asignaciones_tecnicas', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_asignaciones_tecnicas_id'))

    op.drop_table('asignaciones_tecnicas')
    # ### end Alembic commands ###
