"""Creacion de tablas Zen-IT

Revision ID: b0985078d43b
Revises: 
Create Date: 2026-03-31 13:56:28.675119

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b0985078d43b'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('usuarios',
    sa.Column('nombre', sa.String(length=100), nullable=False),
    sa.Column('email', sa.String(length=100), nullable=False),
    sa.Column('hashed_password', sa.String(), nullable=False),
    sa.Column('rol', sa.String(length=20), nullable=True),
    sa.Column('zona', sa.String(length=50), nullable=True),
    sa.Column('departamento', sa.String(length=50), nullable=True),
    sa.Column('centro_costo', sa.String(length=50), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=True),
    sa.Column('tecnico_preferente_id', sa.Integer(), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['tecnico_preferente_id'], ['usuarios.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_usuarios_email'), 'usuarios', ['email'], unique=True)
    op.create_index(op.f('ix_usuarios_id'), 'usuarios', ['id'], unique=False)
    op.create_table('activos',
    sa.Column('numero_serie', sa.String(length=100), nullable=True),
    sa.Column('modelo', sa.String(length=150), nullable=True),
    sa.Column('marca', sa.String(length=100), nullable=True),
    sa.Column('proveedor', sa.String(length=100), nullable=True),
    sa.Column('costo', sa.Float(), nullable=True),
    sa.Column('estatus_operativo', sa.String(length=50), nullable=True),
    sa.Column('usuario_asignado_id', sa.Integer(), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['usuario_asignado_id'], ['usuarios.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_activos_id'), 'activos', ['id'], unique=False)
    op.create_index(op.f('ix_activos_numero_serie'), 'activos', ['numero_serie'], unique=True)
    op.create_table('tickets',
    sa.Column('titulo', sa.String(length=200), nullable=False),
    sa.Column('descripcion', sa.Text(), nullable=False),
    sa.Column('sla_prioridad', sa.String(length=20), nullable=False),
    sa.Column('estatus', sa.String(length=20), nullable=True),
    sa.Column('usuario_id', sa.Integer(), nullable=False),
    sa.Column('tecnico_id', sa.Integer(), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['tecnico_id'], ['usuarios.id'], ),
    sa.ForeignKeyConstraint(['usuario_id'], ['usuarios.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_tickets_id'), 'tickets', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_tickets_id'), table_name='tickets')
    op.drop_table('tickets')
    op.drop_index(op.f('ix_activos_numero_serie'), table_name='activos')
    op.drop_index(op.f('ix_activos_id'), table_name='activos')
    op.drop_table('activos')
    op.drop_index(op.f('ix_usuarios_id'), table_name='usuarios')
    op.drop_index(op.f('ix_usuarios_email'), table_name='usuarios')
    op.drop_table('usuarios')
    # ### end Alembic commands ###
