"""add_documento_licencia_model

Revision ID: bbfbef31a0f7
Revises: 70b70a80622c
Create Date: 2026-06-25 13:09:47.534503

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import sqlite

# revision identifiers, used by Alembic.
revision: str = 'bbfbef31a0f7'
down_revision: Union[str, Sequence[str], None] = '70b70a80622c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('licencias', schema=None) as batch_op:
        batch_op.drop_column('documentos')

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('licencias', schema=None) as batch_op:
        batch_op.add_column(sa.Column('documentos', sqlite.JSON(), nullable=True))

    # ### end Alembic commands ###
