"""add_adjuntos_to_tickets_and_comentarios

Revision ID: da490a75f45b
Revises: 0f820c8ff5a5
Create Date: 2026-07-13 15:04:32.793479

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'da490a75f45b'
down_revision: Union[str, Sequence[str], None] = '0f820c8ff5a5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('comentarios', schema=None) as batch_op:
        batch_op.add_column(sa.Column('adjunto_url', sa.String(length=500), nullable=True))
        batch_op.add_column(sa.Column('adjunto_nombre', sa.String(length=200), nullable=True))

    with op.batch_alter_table('tickets', schema=None) as batch_op:
        batch_op.add_column(sa.Column('adjunto_url', sa.String(length=500), nullable=True))
        batch_op.add_column(sa.Column('adjunto_nombre', sa.String(length=200), nullable=True))

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('tickets', schema=None) as batch_op:
        batch_op.drop_column('adjunto_nombre')
        batch_op.drop_column('adjunto_url')

    with op.batch_alter_table('comentarios', schema=None) as batch_op:
        batch_op.drop_column('adjunto_nombre')
        batch_op.drop_column('adjunto_url')

    # ### end Alembic commands ###
